language: python
matrix:
  include:
    - python: 2.6
      env:
        - SCIPY_VER="0.8.0"
        - NUMPY_VER="1.4.1"
    - python: 2.6
      env:
        - SCIPY_VER="0.14.0"
        - NUMPY_VER="1.9.1"
    - python: 2.7
      env:
        - SCIPY_VER="0.8.0"
        - NUMPY_VER="1.4.1"
    - python: 2.7
      env:
        - SCIPY_VER="0.14.0"
        - NUMPY_VER="1.9.1"
    - python: 3.3
      env:
        - SCIPY_VER="0.8.0"
        - NUMPY_VER="1.5"
    - python: 3.3
      env:
        - SCIPY_VER="0.14.0"
        - NUMPY_VER="1.9.1"
    - python: 3.4
      env:
        - SCIPY_VER="0.8.0"
        - NUMPY_VER="1.5"
    - python: 3.4
      env:
        - SCIPY_VER="0.14.0"
        - NUMPY_VER="1.9.1"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libblas-dev liblapack-dev gfortran
  - "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm"
install:
  - pip install numpy==$NUMPY_VER
  - pip install scipy==$SCIPY_VER
  - pip install -e .
script: python setup.py test
